import type { ScenarioDefinition } from '../../sim/scenario-types';

// OP 0141 "Maple Street": uncertain occupancy, low time pressure. The east bedroom
// is an amber UNKNOWN until an action changes what the team knows. Rushing in
// carries real risk; careful contact and verification pay off. Truth (engine
// only): one resident is in the east bedroom (by the bed, near the east window),
// nobody else is in the house.
//
// Where squads stand matters: voice through the hall door is clearer than through the
// double-glazed east window; looking in through the east window is dim behind the blinds;
// the kitchen 'movement' report can be checked through the glazed back door or the
// front window; heat reads only along a near-clear path.
export const MS_OCCUPANCY: ScenarioDefinition = {
  id: 'ms_occupancy',
  version: 1,
  code: 'OP 0141',
  title: 'Maple Street',
  setting: 'residential',
  locationFamilyId: 'maple_street',
  locationSeed: 0,
  summary: 'A welfare check at a quiet bungalow. The resident has stopped answering and nobody agrees who is inside.',
  variantLabel: 'Uncertain occupancy',
  pressureLabel: 'Low time pressure',
  squadRange: { min: 1, max: 3 },
  briefing: {
    known: ['Welfare check requested by a relative.', 'Doors are closed; no sign of forced access.'],
    unknown: ['Who is in the east bedroom, if anyone.'],
  },
  facts: [
    {
      id: 'f_occ_e',
      label: 'Occupancy of the east bedroom',
      spaceId: 'bedroom_e',
      truth: true,
      initial: 'unknown',
      showWhenUnknown: true,
      markers: { unknown: 'UNKNOWN', reported: 'OCCUPIED?', confirmed: 'OCCUPIED', disproved: 'EMPTY' },
      claim: 'Nobody has confirmed whether anyone is in the east bedroom.',
      source: null,
      note: 'Hearing a voice, seeing movement or reading heat in the room would settle it.',
      resolved: { confirmed: 'One resident is by the bed, near the east window.', disproved: 'The room is empty.' },
      person: { label: 'Resident', at: { x: 42.5, y: 9.2 } },
      uncertainty: 'Whether anyone is in the east bedroom',
    },
    {
      id: 'f_second',
      label: "Neighbour's report of a second person",
      spaceId: 'kitchen',
      truth: false,
      initial: 'reported',
      showWhenUnknown: true,
      markers: { reported: 'MOVEMENT?', confirmed: 'SECOND PERSON', disproved: 'CLEAR' },
      markerSource: 'per neighbour',
      claim: 'A neighbour thinks someone else was moving about in the kitchen, near the dining table.',
      source: 'Neighbour (unverified)',
      note: 'Looking in through the glazed back door or the front window would settle it; so would a steady watch of the house.',
      resolved: { disproved: 'The kitchen was checked: nobody is there.', confirmed: 'Someone else is in the kitchen.' },
      person: { label: 'Movement', reportedAt: { x: 33.5, y: 26.7 } },
      reportedText: 'A neighbour thinks someone else was moving in the kitchen.',
      uncertainty: 'Whether a second person is in the house',
    },
  ],
  objectives: [
    { id: 'o_resolve', label: 'Bring the situation to a safe end' },
    { id: 'o_info', label: 'Keep what the team learns for whoever takes over' },
  ],
  pressure: { start: 12, perMinute: 0.35, threshold: 75, civilianPerMinute: 1 },
  stages: {
    assess: {
      id: 'assess',
      label: 'Assess',
      prompt: 'Nobody has confirmed who is in the east bedroom.',
      actions: [
        {
          id: 'ms_contact',
          stage: 'assess',
          title: 'Make contact',
          icon: 'radio',
          summary: '{lead} ready',
          targetId: 'bedroom_e',
          task: 'Contact',
          requires: { certs: ['crisis_negotiation'], anyTags: ['throw_phone', 'hailer'] },
          check: {
            kind: 'contact',
            ratings: [
              { key: 'communication', weight: 0.6 },
              { key: 'composure', weight: 0.4 },
            ],
            difficulty: 48,
          },
          approach: 'window',
          spatial: { channel: 'sound', subjectFactId: 'f_occ_e', weight: 16, noun: 'Voice' },
          workload: { base: 3, perSqFt: 0 },
          maxParticipants: 2,
          stressBase: 5,
          equipment: [
            { tag: 'throw_phone', value: 10, group: 'line', range: 'opening', label: 'a two-way line into the room' },
            { tag: 'hailer', value: 4, group: 'line', range: 'target', label: 'one-way announcements only' },
          ],
          outcomes: {
            favorable: [
              {
                knowledge: [{ factId: 'f_occ_e', status: 'confirmed' }],
                setFlags: ['in_contact', 'resident_cooperating'],
                objective: 25,
                pressure: -6,
                stage: 'adapt',
                text: 'A resident answered and said they are alone in the east bedroom.',
              },
              {
                when: { facts: [{ factId: 'f_second', in: ['reported'] }] },
                setFlags: ['conflicting_reports'],
                text: "The resident's account does not match the neighbour's report.",
              },
            ],
            mixed: [
              {
                knowledge: [{ factId: 'f_occ_e', status: 'reported' }],
                setFlags: ['in_contact'],
                objective: 10,
                stage: 'adapt',
                text: 'A voice answered but would not say who else is inside.',
              },
              {
                when: { facts: [{ factId: 'f_second', in: ['reported'] }] },
                setFlags: ['conflicting_reports'],
              },
            ],
            adverse: [{ setFlags: ['contact_refused'], pressure: 8, text: 'There was no answer and the attempt raised tension.' }],
          },
        },
        {
          id: 'ms_contact_hall',
          stage: 'assess',
          title: 'Call at the bedroom door',
          icon: 'door',
          summary: 'Clearer voice, from inside',
          targetId: 'bedroom_e',
          task: 'Door',
          requires: { certs: ['crisis_negotiation'], anyTags: ['throw_phone', 'hailer'] },
          check: {
            kind: 'contact',
            ratings: [
              { key: 'communication', weight: 0.6 },
              { key: 'composure', weight: 0.4 },
            ],
            difficulty: 48,
          },
          approach: 'path',
          spatial: { channel: 'sound', subjectFactId: 'f_occ_e', weight: 16, noun: 'Voice' },
          workload: { base: 3, perSqFt: 0 },
          maxParticipants: 2,
          stressBase: 7,
          equipment: [
            { tag: 'throw_phone', value: 10, group: 'line', range: 'opening', label: 'a two-way line under the door' },
            { tag: 'hailer', value: 4, group: 'line', range: 'target', label: 'one-way announcements only' },
          ],
          outcomes: {
            favorable: [
              {
                knowledge: [{ factId: 'f_occ_e', status: 'confirmed' }],
                setFlags: ['in_contact', 'resident_cooperating'],
                openings: [{ openingId: 'd_hall_bede', state: 'open' }],
                objective: 25,
                pressure: -6,
                stage: 'adapt',
                text: 'The resident answered through the door, opened it a hand\'s width and said they are alone.',
              },
              {
                when: { facts: [{ factId: 'f_second', in: ['reported'] }] },
                setFlags: ['conflicting_reports'],
                text: "The resident's account does not match the neighbour's report.",
              },
            ],
            mixed: [
              {
                knowledge: [{ factId: 'f_occ_e', status: 'reported' }],
                setFlags: ['in_contact'],
                objective: 10,
                stage: 'adapt',
                text: 'A voice answered behind the door but would not say who else is inside.',
              },
              {
                when: { facts: [{ factId: 'f_second', in: ['reported'] }] },
                setFlags: ['conflicting_reports'],
              },
            ],
            adverse: [{ setFlags: ['contact_refused'], pressure: 10, text: 'There was no answer and standing at the door raised tension.' }],
          },
        },
        {
          id: 'ms_gather',
          stage: 'assess',
          title: 'Gather intel',
          icon: 'intel',
          summary: 'Takes more time',
          targetId: 'bedroom_e',
          task: 'Observe',
          requires: {},
          check: {
            kind: 'observation',
            ratings: [
              { key: 'awareness', weight: 0.7 },
              { key: 'coordination', weight: 0.3 },
            ],
            difficulty: 44,
          },
          approach: 'window',
          spatial: { channel: 'visual', subjectFactId: 'f_occ_e', weight: 16, noun: 'Sightline' },
          workload: { base: 4, perSqFt: 0.05 },
          stressBase: 3,
          outcomes: {
            favorable: [
              {
                knowledge: [{ factId: 'f_occ_e', status: 'confirmed' }],
                objective: 15,
                stage: 'adapt',
                text: 'Movement was seen through the east window: one person is in the room.',
              },
            ],
            mixed: [
              {
                knowledge: [{ factId: 'f_occ_e', status: 'reported' }],
                objective: 8,
                stage: 'adapt',
                text: 'There are signs of movement but nothing conclusive.',
              },
            ],
            adverse: [{ pressure: 3, text: 'The watch turned up nothing conclusive.' }],
          },
        },
      ],
    },
    adapt: {
      id: 'adapt',
      label: 'Adapt',
      prompt: 'Reports disagree. Verify them, or save time and accept the doubt.',
      actions: [
        {
          id: 'ms_thermal',
          stage: 'adapt',
          title: 'Thermal check',
          icon: 'thermal',
          summary: 'Uses a battery pack',
          targetId: 'bedroom_e',
          task: 'Thermal',
          requires: { allTags: ['thermal'] },
          check: {
            kind: 'observation',
            ratings: [
              { key: 'awareness', weight: 0.7 },
              { key: 'composure', weight: 0.3 },
            ],
            difficulty: 38,
          },
          approach: 'path',
          spatial: { channel: 'thermal', subjectFactId: 'f_occ_e', weight: 22, noun: 'Heat' },
          workload: { base: 2, perSqFt: 0.01 },
          stressBase: 3,
          consumes: [{ tag: 'battery', qty: 1 }],
          equipment: [{ tag: 'thermal', value: 4, range: 'target', label: 'a heat reading, range permitting' }],
          certBonus: { cert: 'surveillance', value: 4, label: 'trained to read thermal images' },
          outcomes: {
            favorable: [
              {
                knowledge: [{ factId: 'f_occ_e', status: 'confirmed' }],
                objective: 10,
                stage: 'resolve',
                text: 'Thermal shows one person by the bed in the east bedroom.',
              },
            ],
            mixed: [
              {
                knowledge: [{ factId: 'f_occ_e', status: 'reported' }],
                objective: 5,
                stage: 'resolve',
                text: 'Thermal shows a faint warm shape in the east bedroom, nothing more.',
              },
            ],
            adverse: [{ pressure: 2, text: 'The thermal image was too muddy to read.' }],
          },
        },
        {
          id: 'ms_perimeter_watch',
          stage: 'adapt',
          title: 'Watch the perimeter',
          icon: 'perimeter',
          summary: 'Slow, quiet, wider with more squads',
          targetId: 'kitchen',
          task: 'Watch',
          requires: {},
          check: {
            kind: 'observation',
            ratings: [
              { key: 'awareness', weight: 0.5 },
              { key: 'composure', weight: 0.3 },
              { key: 'coordination', weight: 0.2 },
            ],
            difficulty: 46,
          },
          tempo: 'waiting',
          approach: 'window',
          spatial: { channel: 'visual', subjectFactId: 'f_second', weight: 14, noun: 'Sightline' },
          workload: { base: 5, perSqFt: 0.02 },
          maxActing: 3,
          coveragePerVantage: 5,
          stressBase: 3,
          outcomes: {
            favorable: [
              {
                knowledge: [{ factId: 'f_second', status: 'disproved' }],
                objective: 8,
                stage: 'resolve',
                text: 'A steady watch showed an empty kitchen: nothing moved at the table or the back door.',
              },
            ],
            mixed: [
              {
                knowledge: [{ factId: 'f_occ_e', status: 'reported' }],
                objective: 4,
                stage: 'resolve',
                text: 'The watch caught movement on the east side but could not place it; the kitchen is still unsettled.',
              },
            ],
            adverse: [{ pressure: 2, text: 'The watch saw too little to change the picture.' }],
          },
        },
        {
          id: 'ms_preserve_time',
          stage: 'adapt',
          title: 'Preserve time',
          icon: 'wait',
          summary: 'Keeps options open',
          targetId: 'bedroom_e',
          task: 'Hold',
          requires: {},
          check: {
            kind: 'pressure',
            ratings: [
              { key: 'composure', weight: 0.6 },
              { key: 'communication', weight: 0.4 },
            ],
            difficulty: 40,
          },
          tempo: 'waiting',
          approach: 'none',
          workload: { base: 3, perSqFt: 0 },
          stressBase: 2,
          outcomes: {
            favorable: [{ pressure: -8, objective: 5, setFlags: ['time_preserved'], stage: 'resolve', text: 'The team held steady and the scene settled.' }],
            mixed: [{ pressure: -3, stage: 'resolve', text: 'The wait settled little, but nothing worsened.' }],
            adverse: [{ pressure: 6, stage: 'resolve', text: 'Waiting without new information made the scene tenser.' }],
          },
        },
      ],
    },
    resolve: {
      id: 'resolve',
      label: 'Resolve',
      prompt: 'Choose how this ends. Information carries into the debrief either way.',
      actions: [
        {
          id: 'ms_negotiated_exit',
          stage: 'resolve',
          title: 'Talk them out',
          icon: 'radio',
          summary: 'Needs the open line',
          targetId: 'bedroom_e',
          task: 'Talking',
          requires: { flags: [{ flag: 'in_contact', reason: 'No open line to the east bedroom yet' }] },
          check: {
            kind: 'contact',
            ratings: [
              { key: 'communication', weight: 0.5 },
              { key: 'composure', weight: 0.5 },
            ],
            difficulty: 52,
          },
          approach: 'none',
          workload: { base: 6, perSqFt: 0 },
          maxParticipants: 2,
          stressBase: 6,
          equipment: [
            { tag: 'throw_phone', value: 6, group: 'line', label: 'keeps the line steady' },
            { tag: 'hailer', value: 2, group: 'line', label: 'one-way only' },
          ],
          modifiers: [
            { label: 'Resident already cooperating', when: { flags: ['resident_cooperating'] }, source: 'preparation', value: 6 },
            { label: 'Rapport built while time was preserved', when: { flags: ['time_preserved'] }, source: 'preparation', value: 4 },
            { label: 'Conflicting reports still unresolved', when: { flags: ['conflicting_reports'], facts: [{ factId: 'f_second', in: ['reported'] }] }, source: 'difficulty', value: 6 },
          ],
          outcomes: {
            favorable: [{ ending: 'peaceful_exit', objective: 65, text: 'The resident came out calmly and nobody was hurt.' }],
            mixed: [{ ending: 'slow_exit', objective: 40, civilian: -3, text: 'The resident came out after a long and tense call.' }],
            adverse: [{ ending: 'transferred_after_talks', objective: 20, civilian: -6, text: 'Talks stalled and responsibility was transferred with the call notes.' }],
          },
        },
        {
          id: 'ms_controlled_entry',
          stage: 'resolve',
          title: 'Controlled entry',
          icon: 'door',
          summary: 'High risk',
          targetId: 'bedroom_e',
          task: 'Entry',
          requires: { certs: ['entry_team'] },
          check: {
            kind: 'execution',
            ratings: [
              { key: 'shooting', weight: 0.3 },
              { key: 'coordination', weight: 0.4 },
              { key: 'composure', weight: 0.3 },
            ],
            difficulty: 50,
          },
          approach: 'path',
          entry: { subjectFactId: 'f_occ_e' },
          workload: { base: 2, perSqFt: 0.01 },
          capacityBound: ['hall', 'bedroom_e'],
          stressBase: 10,
          equipment: [{ tag: 'shield', value: 5, narrowValue: 9, label: 'reduces exposure for the lead in the narrow hall' }],
          support: { max: 12, coverSpaceId: 'side_yard_e', reachMinutes: 10, maxSquads: 2, label: 'covering the east side', task: 'Cover' },
          modifiers: [
            { label: 'Occupancy not confirmed', when: { facts: [{ factId: 'f_occ_e', in: ['unknown', 'reported'] }] }, source: 'difficulty', value: 8 },
          ],
          outcomes: {
            favorable: [
              { ending: 'entry_secured', objective: 45, civilian: -6, text: 'The room was entered and secured.' },
              { when: { facts: [{ factId: 'f_occ_e', in: ['unknown', 'reported'] }] }, civilian: -18, text: 'Entering before the room was confirmed put the occupant at risk.' },
              { when: { flags: ['resident_cooperating'] }, civilian: -6, text: 'The resident had been cooperating, so entry was not needed.' },
            ],
            mixed: [
              { ending: 'entry_costly', objective: 30, civilian: -14, text: 'Entry was slow and the room was only partly under control.' },
              { when: { facts: [{ factId: 'f_occ_e', in: ['unknown', 'reported'] }] }, civilian: -14, text: 'Entering before the room was confirmed put the occupant at risk.' },
              { when: { flags: ['resident_cooperating'] }, civilian: -6, text: 'The resident had been cooperating, so entry was not needed.' },
            ],
            adverse: [
              { ending: 'entry_costly', objective: 15, civilian: -26, pressure: 15, text: 'Entry went badly and the situation escalated.' },
              { when: { facts: [{ factId: 'f_occ_e', in: ['unknown', 'reported'] }] }, civilian: -10, text: 'Nobody had confirmed who was in the room.' },
            ],
          },
        },
        {
          id: 'ms_handover',
          stage: 'resolve',
          title: 'Hand over to specialists',
          icon: 'handover',
          summary: 'Always available',
          targetId: 'bedroom_e',
          task: 'Handover',
          requires: {},
          check: {
            kind: 'coordination',
            ratings: [
              { key: 'communication', weight: 0.5 },
              { key: 'coordination', weight: 0.5 },
            ],
            difficulty: 30,
          },
          approach: 'none',
          workload: { base: 4, perSqFt: 0 },
          stressBase: 2,
          outcomes: {
            favorable: [
              { ending: 'handed_over', objective: 45, text: 'Notes and map markers went to specialist support cleanly.' },
              { when: { facts: [{ factId: 'f_occ_e', in: ['confirmed'] }] }, objective: 10, text: 'The confirmed occupancy gave the specialists a head start.' },
            ],
            mixed: [{ ending: 'handed_over', objective: 35, text: 'Specialists took over with a few gaps to fill.' }],
            adverse: [{ ending: 'handed_over', objective: 25, civilian: -2, text: 'The handover was rough and some detail was lost.' }],
          },
        },
      ],
    },
  },
  endings: {
    peaceful_exit: { id: 'peaceful_exit', title: 'Resident came out safely', summary: 'Contact led to a calm, voluntary exit.', trustAdjust: 1, strain: -2 },
    slow_exit: { id: 'slow_exit', title: 'Resident came out after a long call', summary: 'It ended well, but not easily.', trustAdjust: 0, strain: 0 },
    transferred_after_talks: { id: 'transferred_after_talks', title: 'Transferred after stalled talks', summary: 'Specialists took over with the call notes.', trustAdjust: 0, strain: 2 },
    entry_secured: { id: 'entry_secured', title: 'Room entered and secured', summary: 'The room was secured by controlled entry.', trustAdjust: -1, strain: 3 },
    entry_costly: { id: 'entry_costly', title: 'Entry led to a harder outcome', summary: 'Entry created more problems than it solved.', trustAdjust: -3, strain: 5 },
    handed_over: { id: 'handed_over', title: 'Handed to specialist support', summary: 'A safe transfer: modest, but nothing was lost.', trustAdjust: 0, strain: 0 },
  },
  rewards: { funding: 1800, devPoints: 2, trust: 4, xp: 30 },
};
