import type { ScenarioDefinition } from '../../sim/scenario-types';

// OP 0142 "Maple Street": a caller reports a resident needs medical help. The
// caller places them in the kitchen, but the engine truth is the east bedroom.
// Pressure climbs with every operation minute; past the threshold civilian safety
// falls. Slow information gathering is expensive here; quick checks and early
// medical response pay off.
export const MS_URGENT: ScenarioDefinition = {
  id: 'ms_urgent',
  version: 1,
  code: 'OP 0142',
  title: 'Maple Street',
  setting: 'residential',
  locationFamilyId: 'maple_street',
  locationSeed: 0,
  summary: 'A caller says a resident needs medical help right now and thinks they are in the kitchen.',
  variantLabel: 'Time pressure',
  pressureLabel: 'High time pressure',
  squadRange: { min: 1, max: 3 },
  briefing: {
    known: ['Medical call: a resident has collapsed or is badly unwell.', 'The caller is outside and unsure of the room.'],
    unknown: ['Where the patient actually is.'],
  },
  facts: [
    {
      id: 'f_kitchen',
      label: "Caller's report: patient in the kitchen",
      spaceId: 'kitchen',
      truth: false,
      initial: 'reported',
      showWhenUnknown: true,
      markers: { reported: 'PATIENT?', confirmed: 'PATIENT', disproved: 'CLEAR' },
      markerSource: 'per caller',
      claim: 'The caller says the patient is on the kitchen floor, near the dining table.',
      source: 'Caller',
      note: 'Looking in through the glazed back door or the front window, or calling the caller back, would settle it.',
      resolved: { disproved: 'The kitchen is empty.', confirmed: 'The patient is in the kitchen.' },
      person: { label: 'Patient', reportedAt: { x: 34.5, y: 23 } },
      reportedText: 'The caller thinks the patient is in the kitchen.',
      uncertainty: 'Whether the patient is where the caller says',
    },
    {
      id: 'f_patient_e',
      label: 'Location of the patient',
      spaceId: 'bedroom_e',
      truth: true,
      initial: 'unknown',
      showWhenUnknown: false,
      markers: { reported: 'PATIENT?', confirmed: 'PATIENT' },
      markerSource: 'heard on scene',
      claim: 'Someone may be calling out from the east side of the house.',
      source: 'Heard on scene',
      note: 'Listening at the hall door or the east window, or a survey of the house, would settle it.',
      resolved: { confirmed: 'The patient is on the floor at the foot of the bed.' },
      person: { label: 'Patient', at: { x: 37, y: 14 } },
      uncertainty: 'Where the patient actually is',
    },
  ],
  objectives: [
    { id: 'o_aid', label: 'Reach the patient and get medical help to them' },
    { id: 'o_time', label: 'Keep the response fast' },
  ],
  pressure: { start: 20, perMinute: 2, threshold: 50, civilianPerMinute: 2.5 },
  stages: {
    assess: {
      id: 'assess',
      label: 'Assess',
      prompt: 'The caller says kitchen. Every minute counts.',
      actions: [
        {
          id: 'mu_call_back',
          stage: 'assess',
          title: 'Call the caller back',
          icon: 'radio',
          summary: 'Quick call',
          targetId: 'kitchen',
          task: 'Calling',
          requires: {},
          check: {
            kind: 'contact',
            ratings: [
              { key: 'communication', weight: 0.6 },
              { key: 'composure', weight: 0.4 },
            ],
            difficulty: 40,
          },
          tempo: 'urgent',
          approach: 'none',
          workload: { base: 2, perSqFt: 0 },
          maxParticipants: 2,
          stressBase: 4,
          outcomes: {
            favorable: [
              {
                knowledge: [
                  { factId: 'f_kitchen', status: 'disproved' },
                  { factId: 'f_patient_e', status: 'reported' },
                ],
                objective: 10,
                stage: 'adapt',
                text: 'The caller corrected themselves: the sounds came from the east side of the house.',
              },
            ],
            mixed: [
              {
                knowledge: [{ factId: 'f_patient_e', status: 'reported' }],
                setFlags: ['conflicting_reports'],
                objective: 4,
                stage: 'adapt',
                text: 'The caller heard something from the east side but is not sure about the kitchen either.',
              },
            ],
            adverse: [{ pressure: 4, text: 'The caller was too distressed to say anything useful.' }],
          },
        },
        {
          id: 'mu_check_reported',
          stage: 'assess',
          title: 'Check the reported room',
          icon: 'search',
          summary: 'Fastest look',
          targetId: 'kitchen',
          task: 'Checking',
          requires: {},
          check: {
            kind: 'observation',
            ratings: [
              { key: 'awareness', weight: 0.6 },
              { key: 'coordination', weight: 0.2 },
              { key: 'composure', weight: 0.2 },
            ],
            difficulty: 42,
          },
          tempo: 'urgent',
          approach: 'window',
          spatial: { channel: 'visual', subjectFactId: 'f_kitchen', weight: 14, noun: 'Sightline' },
          workload: { base: 1, perSqFt: 0.008 },
          stressBase: 5,
          outcomes: {
            favorable: [
              {
                knowledge: [
                  { factId: 'f_kitchen', status: 'disproved' },
                  { factId: 'f_patient_e', status: 'confirmed' },
                ],
                objective: 15,
                stage: 'adapt',
                text: 'The kitchen was empty from the glazed back door, and a faint call came from the east bedroom.',
              },
            ],
            mixed: [
              {
                knowledge: [
                  { factId: 'f_kitchen', status: 'disproved' },
                  { factId: 'f_patient_e', status: 'reported' },
                ],
                objective: 8,
                stage: 'adapt',
                text: 'The kitchen was empty; a sound from the east side is the only lead.',
              },
            ],
            adverse: [{ pressure: 3, text: 'The kitchen check was slow and told the team little.' }],
          },
        },
        {
          id: 'mu_survey_house',
          stage: 'assess',
          title: 'Survey the house',
          icon: 'intel',
          summary: 'Thorough, slow',
          targetId: 'hall',
          task: 'Surveying',
          requires: {},
          check: {
            kind: 'observation',
            ratings: [
              { key: 'awareness', weight: 0.7 },
              { key: 'coordination', weight: 0.3 },
            ],
            difficulty: 34,
          },
          approach: 'path',
          workload: { base: 3, perSqFt: 0.012, areaSpaces: ['living', 'kitchen', 'hall', 'bedroom_w', 'bath', 'bedroom_e'] },
          stressBase: 4,
          outcomes: {
            favorable: [
              {
                knowledge: [
                  { factId: 'f_kitchen', status: 'disproved' },
                  { factId: 'f_patient_e', status: 'confirmed' },
                ],
                setFlags: ['house_mapped'],
                objective: 20,
                stage: 'adapt',
                text: 'A full survey found the patient in the east bedroom and cleared the kitchen.',
              },
            ],
            mixed: [
              {
                knowledge: [
                  { factId: 'f_kitchen', status: 'disproved' },
                  { factId: 'f_patient_e', status: 'reported' },
                ],
                objective: 10,
                stage: 'adapt',
                text: 'The survey cleared the kitchen and pointed to the east side.',
              },
            ],
            adverse: [{ pressure: 2, text: 'The survey took a long time and settled nothing.' }],
          },
        },
      ],
    },
    adapt: {
      id: 'adapt',
      label: 'Adapt',
      prompt: 'Decide how to get care to the patient.',
      actions: [
        {
          id: 'mu_two_point',
          stage: 'adapt',
          title: 'Two-point approach',
          icon: 'door',
          summary: 'Needs two squads',
          targetId: 'kitchen',
          task: 'Approach',
          requires: {
            minSquads: { count: 2, reason: 'Needs a second squad to cover the back door' },
            openings: [
              {
                openingId: 'd_back',
                blockedReason: 'Back door is blocked: there is no second route',
                lockedTag: 'entry_tool',
                lockedNote: 'Back door is locked: takes longer without a door ram',
              },
            ],
          },
          check: {
            kind: 'coordination',
            ratings: [
              { key: 'coordination', weight: 0.6 },
              { key: 'communication', weight: 0.2 },
              { key: 'composure', weight: 0.2 },
            ],
            difficulty: 40,
          },
          tempo: 'urgent',
          approach: 'path',
          workload: { base: 2, perSqFt: 0 },
          stressBase: 5,
          support: { max: 14, coverSpaceId: 'kitchen', reachMinutes: 8, maxSquads: 2, label: 'covering the back door', task: 'Back door', openingId: 'd_back' },
          outcomes: {
            favorable: [
              {
                setFlags: ['two_point_set'],
                openings: [{ openingId: 'd_back', state: 'open' }],
                objective: 8,
                stage: 'resolve',
                text: 'Two routes into the house are open and both squads know their part.',
              },
            ],
            mixed: [{ setFlags: ['two_point_set'], stage: 'resolve', text: 'Both routes are covered, though the timing was loose.' }],
            adverse: [{ pressure: 3, text: 'The squads lost time lining up the second route.' }],
          },
        },
        {
          id: 'mu_stage_medic',
          stage: 'adapt',
          title: 'Stage medical aid',
          icon: 'medic',
          summary: '{lead} ready',
          targetId: 'living',
          task: 'Staged',
          requires: { certs: ['advanced_first_aid'] },
          check: {
            kind: 'medical',
            ratings: [
              { key: 'medical', weight: 0.5 },
              { key: 'composure', weight: 0.3 },
              { key: 'coordination', weight: 0.2 },
            ],
            difficulty: 36,
          },
          tempo: 'urgent',
          approach: 'none',
          workload: { base: 3, perSqFt: 0 },
          stressBase: 3,
          outcomes: {
            favorable: [{ setFlags: ['medic_staged'], objective: 8, stage: 'resolve', text: 'The medic had the kit open and the route clear before moving in.' }],
            mixed: [{ setFlags: ['medic_staged'], stage: 'resolve', text: 'The medic was staged, with some kit still to sort.' }],
            adverse: [{ pressure: 2, text: 'Staging the kit cost minutes without helping.' }],
          },
        },
        {
          id: 'mu_go_now',
          stage: 'adapt',
          title: 'Go in now',
          icon: 'door',
          summary: 'Saves minutes',
          targetId: 'hall',
          task: 'Committed',
          requires: {},
          check: {
            kind: 'coordination',
            ratings: [
              { key: 'coordination', weight: 0.5 },
              { key: 'composure', weight: 0.5 },
            ],
            difficulty: 30,
          },
          tempo: 'urgent',
          approach: 'none',
          workload: { base: 1, perSqFt: 0 },
          stressBase: 6,
          outcomes: {
            favorable: [{ setFlags: ['committed_early'], pressure: -4, objective: 4, stage: 'resolve', text: 'The team committed early and kept the pace.' }],
            mixed: [{ setFlags: ['committed_early'], stage: 'resolve', text: 'The team went in without much preparation.' }],
            adverse: [{ setFlags: ['committed_early'], pressure: 4, stage: 'resolve', text: 'The team went in ragged and the pace suffered.' }],
          },
        },
      ],
    },
    resolve: {
      id: 'resolve',
      label: 'Resolve',
      prompt: 'Get care to the patient, or hand over to medical responders.',
      actions: [
        {
          id: 'mu_targeted_aid',
          stage: 'resolve',
          title: 'Go to the patient',
          icon: 'medic',
          summary: 'Uses a trauma kit',
          targetId: 'bedroom_e',
          task: 'Aid',
          requires: {
            certs: ['advanced_first_aid'],
            allTags: ['medkit'],
            facts: [{ factId: 'f_patient_e', in: ['reported', 'confirmed'], reason: "The patient's location is not known yet" }],
          },
          check: {
            kind: 'medical',
            ratings: [
              { key: 'medical', weight: 0.6 },
              { key: 'composure', weight: 0.2 },
              { key: 'coordination', weight: 0.2 },
            ],
            difficulty: 46,
          },
          tempo: 'urgent',
          approach: 'path',
          entry: { subjectFactId: 'f_patient_e' },
          workload: { base: 3, perSqFt: 0.02 },
          capacityBound: ['bedroom_e'],
          stressBase: 8,
          consumes: [{ tag: 'medkit', qty: 1 }],
          equipment: [{ tag: 'medkit', value: 6, label: 'kit ready at the bedside' }],
          modifiers: [
            { label: 'Location confirmed', when: { facts: [{ factId: 'f_patient_e', in: ['confirmed'] }] }, source: 'preparation', value: 6 },
            { label: 'Location only reported', when: { facts: [{ factId: 'f_patient_e', in: ['reported'] }] }, source: 'difficulty', value: 6 },
            { label: 'Medical kit already staged', when: { flags: ['medic_staged'] }, source: 'preparation', value: 8 },
            { label: 'Second route open', when: { flags: ['two_point_set'] }, source: 'preparation', value: 5 },
          ],
          outcomes: {
            favorable: [{ ending: 'patient_stabilized', objective: 70, text: 'The patient was reached quickly and stabilized.' }],
            mixed: [{ ending: 'patient_treated_late', objective: 50, civilian: -10, text: 'The patient was treated, but later than hoped.' }],
            adverse: [{ ending: 'aid_delayed', objective: 30, civilian: -22, text: 'Care reached the patient late and the condition worsened.' }],
          },
        },
        {
          id: 'mu_sweep_and_aid',
          stage: 'resolve',
          title: 'Search and treat',
          icon: 'search',
          summary: 'Search while treating',
          targetId: 'hall',
          task: 'Sweeping',
          requires: { certs: ['advanced_first_aid'], allTags: ['medkit'] },
          check: {
            kind: 'medical',
            ratings: [
              { key: 'medical', weight: 0.5 },
              { key: 'awareness', weight: 0.3 },
              { key: 'coordination', weight: 0.2 },
            ],
            difficulty: 52,
          },
          tempo: 'urgent',
          approach: 'path',
          workload: { base: 4, perSqFt: 0.02, areaSpaces: ['bedroom_w', 'bath', 'bedroom_e'] },
          stressBase: 9,
          consumes: [{ tag: 'medkit', qty: 1 }],
          equipment: [{ tag: 'medkit', value: 6, label: 'kit ready' }],
          modifiers: [
            { label: 'Medical kit already staged', when: { flags: ['medic_staged'] }, source: 'preparation', value: 8 },
            { label: 'Second route open', when: { flags: ['two_point_set'] }, source: 'preparation', value: 5 },
          ],
          outcomes: {
            favorable: [{ ending: 'patient_stabilized', objective: 65, text: 'The sweep found the patient and care began at once.' }],
            mixed: [{ ending: 'patient_treated_late', objective: 45, civilian: -10, text: 'The sweep found the patient, but searching cost time.' }],
            adverse: [{ ending: 'aid_delayed', objective: 25, civilian: -22, text: 'The search ran long and care started late.' }],
          },
        },
        {
          id: 'mu_handover',
          stage: 'resolve',
          title: 'Hand over to medics',
          icon: 'handover',
          summary: 'Always available',
          targetId: 'hall',
          task: 'Handover',
          requires: {},
          check: {
            kind: 'coordination',
            ratings: [
              { key: 'communication', weight: 0.5 },
              { key: 'coordination', weight: 0.5 },
            ],
            difficulty: 28,
          },
          approach: 'none',
          workload: { base: 5, perSqFt: 0 },
          stressBase: 2,
          outcomes: {
            favorable: [
              { ending: 'handed_to_ems', objective: 45, text: 'Medical responders were guided straight in.' },
              { when: { facts: [{ factId: 'f_patient_e', in: ['unknown'] }] }, civilian: -8, text: 'Responders arrived without knowing which room to go to.' },
            ],
            mixed: [
              { ending: 'handed_to_ems', objective: 35, text: 'Responders took over after a short delay.' },
              { when: { facts: [{ factId: 'f_patient_e', in: ['unknown'] }] }, civilian: -8, text: 'Responders arrived without knowing which room to go to.' },
            ],
            adverse: [
              { ending: 'handed_to_ems', objective: 25, civilian: -6, text: 'The handover was rough and cost minutes.' },
              { when: { facts: [{ factId: 'f_patient_e', in: ['unknown'] }] }, civilian: -8, text: 'Responders arrived without knowing which room to go to.' },
            ],
          },
        },
      ],
    },
  },
  endings: {
    patient_stabilized: { id: 'patient_stabilized', title: 'Patient stabilized', summary: 'Care reached the patient in time.', trustAdjust: 1, strain: -1 },
    patient_treated_late: { id: 'patient_treated_late', title: 'Patient treated, later than hoped', summary: 'Care arrived, but the delay mattered.', trustAdjust: 0, strain: 2 },
    aid_delayed: { id: 'aid_delayed', title: 'Aid was delayed', summary: 'The patient waited too long for care.', trustAdjust: -2, strain: 4 },
    handed_to_ems: { id: 'handed_to_ems', title: 'Handed to medical responders', summary: 'A safe transfer to the people best placed to help.', trustAdjust: 0, strain: 0 },
    handed_over: { id: 'handed_over', title: 'Handed over', summary: 'Responsibility was transferred.', trustAdjust: 0, strain: 0 },
  },
  rewards: { funding: 1600, devPoints: 2, trust: 4, xp: 28 },
};
