import type { ItemDefinition } from '../sim/types';

// Abstract game equipment. Tags are what actions require; names are flavour.
// Wear and range values are proposed tuning. Each physical unit wears on its own.
export const ITEMS: Record<string, ItemDefinition> = {
  radio_kit: {
    id: 'radio_kit',
    name: 'Radio headset',
    kind: 'equipment',
    cost: 400,
    tags: ['comms_kit'],
    description: 'Keeps squads in contact across rooms and with each other.',
    wear: { perUse: 6, perDay: 0.15, unreliableBelow: 45, failAt: 15, serviceHours: 3, serviceCost: 60, restoreTo: 92 },
    range: { effective: 600, max: 1500 },
  },
  loud_hailer: {
    id: 'loud_hailer',
    name: 'Loud hailer',
    kind: 'equipment',
    cost: 250,
    tags: ['hailer'],
    description: 'One-way announcements from outside. Basic contact without a negotiator.',
    wear: { perUse: 3, perDay: 0.05, unreliableBelow: 40, failAt: 10, serviceHours: 2, serviceCost: 30, restoreTo: 95 },
    range: { effective: 60, max: 120 },
  },
  throw_phone: {
    id: 'throw_phone',
    name: 'Throw phone',
    kind: 'equipment',
    cost: 900,
    tags: ['throw_phone'],
    requiresNode: 'field_contact_kit',
    description: 'Two-way line for a qualified negotiator.',
    wear: { perUse: 10, perDay: 0.1, unreliableBelow: 50, failAt: 20, serviceHours: 4, serviceCost: 120, restoreTo: 90 },
    range: { effective: 20, max: 35 },
  },
  thermal_imager: {
    id: 'thermal_imager',
    name: 'Thermal imager',
    kind: 'equipment',
    cost: 1500,
    tags: ['thermal'],
    requiresNode: 'intel_thermal',
    description: 'Reads heat signatures in line of sight. Walls and glass block most of it; an open door or gap works best. Uses a battery pack.',
    wear: { perUse: 5, perDay: 0.2, unreliableBelow: 50, failAt: 20, serviceHours: 6, serviceCost: 200, restoreTo: 90 },
    range: { effective: 40, max: 80 },
  },
  camera_drone: {
    id: 'camera_drone',
    name: 'Camera drone',
    kind: 'equipment',
    cost: 2200,
    tags: ['drone'],
    requiresNode: 'intel_drone',
    description: 'Indoor survey by a certified operator. Uses a battery pack.',
    wear: { perUse: 12, perDay: 0.1, unreliableBelow: 55, failAt: 25, serviceHours: 8, serviceCost: 260, restoreTo: 88 },
    range: { effective: 150, max: 300 },
  },
  ballistic_shield: {
    id: 'ballistic_shield',
    name: 'Ballistic shield',
    kind: 'equipment',
    cost: 1200,
    tags: ['shield'],
    description: 'Reduces exposure for the lead officer in narrow spaces.',
    wear: { perUse: 4, perDay: 0.02, unreliableBelow: 40, failAt: 10, serviceHours: 4, serviceCost: 80, restoreTo: 95 },
  },
  door_ram: {
    id: 'door_ram',
    name: 'Door ram',
    kind: 'equipment',
    cost: 300,
    tags: ['entry_tool'],
    description: 'Opens a locked door quickly. Noisy.',
    wear: { perUse: 3, perDay: 0.01, unreliableBelow: 30, failAt: 5, serviceHours: 1, serviceCost: 20, restoreTo: 98 },
  },
  trauma_kit: {
    id: 'trauma_kit',
    name: 'Trauma kit',
    kind: 'consumable',
    cost: 120,
    tags: ['medkit'],
    description: 'Consumed when used for stabilisation.',
    wear: { perUse: 100, perDay: 0, unreliableBelow: 0, failAt: 0, serviceHours: 0, serviceCost: 0, restoreTo: 0, shelfLifeDays: 540 },
  },
  battery_pack: {
    id: 'battery_pack',
    name: 'Battery pack',
    kind: 'consumable',
    cost: 40,
    tags: ['battery'],
    description: 'Consumed by thermal and drone use.',
    wear: { perUse: 100, perDay: 0.4, unreliableBelow: 50, failAt: 20, serviceHours: 0, serviceCost: 0, restoreTo: 0, shelfLifeDays: 365 },
  },
};
