import { describe, expect, it } from 'vitest';
import activeV4Text from './fixtures/release-v4-active.json?raw';
import stacksV1Text from './fixtures/release-v1-stacks.json?raw';
import expectedV4Text from './fixtures/release-v1-expected-v4.json?raw';
import { createInitialState } from './department';
import { dispatch } from './game';
import { CURRENT_SAVE_VERSION, deserialize, serialize } from './save';
import { INCIDENT_CONTENT_VERSION } from '../gen/incident';
import { decisionViews, actionViews, briefing } from './operation-selectors';
import { startCmd, playPolicy } from './test-fixtures';
import { squadTopology } from './squad-optimizer';
import type { Command, GameState } from './types';

// Frozen output of the published tree (local commit 92ab37d), never generated by
// the implementation under test. See fixtures/README.md for provenance.
const v4 = () => JSON.parse(activeV4Text);
const NOW = v4().savedAt as number;
const batteries = (state: GameState) => Object.values(state.units).filter((unit) => unit.itemId === 'battery_pack');
const apply = (state: GameState, command: Command) => {
  const result = dispatch(state, command, { now: NOW });
  expect(result.result, JSON.stringify(command)).toEqual({ ok: true });
  return result.state;
};

function currentDecisionState(): GameState {
  const scenarioId = 'exercise_welfare_v3';
  let state = createInitialState(NOW, 507);
  state = apply(state, startCmd(scenarioId, ['A'], {
    positions: { A: briefing(scenarioId).entries[0].id }, loadouts: { A: {} }, practice: true,
  }));
  const first = actionViews(state, NOW, 'A').find((action) => action.eligible)!;
  state = apply(state, { type: 'decide', actionId: first.id, actingSquadIds: first.actingSquadIds, supportSquadIds: first.supportSquadIds });
  expect(state.activeRun!.history[0].committed).toBeDefined();
  return state;
}

describe('published v4 saves upgraded to integrated power and tiered development', () => {
  it('uses a genuine prior-version envelope containing legacy power stock and a consumed battery', () => {
    const raw = v4();
    expect(raw.saveVersion).toBe(4);
    expect(raw.state.saveVersion).toBe(4);
    expect(raw.contentVersion).toBe(2);
    expect(raw.state.department).not.toHaveProperty('developmentTiers');
    expect(batteries(raw.state)).toHaveLength(6);
    expect(raw.state.activeRun.history[1].itemsConsumed).toContainEqual({ itemId: 'battery_pack', qty: 1 });
  });

  it('refunds exactly four unconsumed nonscrapped units, including expired and reserved units', () => {
    const raw = v4();
    const before = raw.state as GameState;
    const loaded = deserialize(activeV4Text)!;
    expect(loaded).not.toBeNull();
    expect(loaded.saveVersion).toBe(5);
    expect(CURRENT_SAVE_VERSION).toBe(5);
    expect(loaded.contentVersion).toBe(INCIDENT_CONTENT_VERSION);
    expect(batteries(loaded)).toEqual([]);
    expect(loaded.department.funding).toBe(before.department.funding + 160);
    expect(loaded.equipmentPowerUpgrade).toEqual({ retiredUnits: 6, refundedFunding: 160 });
    expect(loaded.department.devPoints).toBe(before.department.devPoints);
    expect(loaded.nextId).toBe(before.nextId);
    expect(loaded.rngState).toBe(before.rngState);
    expect(loaded.officers).toEqual(before.officers);
    expect(loaded.candidates).toEqual(before.candidates);
    expect(loaded.personnel).toEqual(before.personnel);
    expect(loaded.incidents).toEqual(before.incidents);
    expect(loaded.units).toEqual(Object.fromEntries(Object.entries(before.units).filter(([, unit]) => unit.itemId !== 'battery_pack')));
    expect(v4()).toEqual(raw);
  });

  it('cleans power reservations, presets and restock rules without dropping elapsed delivery time or operation history', () => {
    const before = v4().state as GameState;
    const loaded = deserialize(activeV4Text)!;
    const kept = before.reservations.filter((reservation) => reservation.itemId !== 'battery_pack');
    const removedIds = new Set(before.reservations.filter((reservation) => reservation.itemId === 'battery_pack').map((reservation) => reservation.id));
    expect(loaded.reservations).toEqual(kept);
    expect(loaded.squads[0].loadoutPreset).toEqual({ radio_kit: 4, thermal_imager: 1 });
    expect(loaded.department.restockRules).toEqual([{ itemId: 'trauma_kit', target: 4, budgetCeiling: 100 }]);
    expect(loaded.activeRun).toEqual({
      ...before.activeRun,
      reservationIds: before.activeRun!.reservationIds.filter((id) => !removedIds.has(id)),
      resupplies: [{ minutes: 3, allocations: [] }],
    });
    expect(loaded.activeRun!.resupplies![0].minutes).toBeGreaterThan(0);
    expect(loaded.activeRun!.history).toEqual(before.activeRun!.history);
    expect(loaded.activeRun!.history[1].itemsConsumed).toContainEqual({ itemId: 'battery_pack', qty: 1 });
    expect(decisionViews(loaded)).toHaveLength(before.activeRun!.history.length);
    expect(deserialize(serialize(loaded, NOW))).toEqual(loaded);
    expect(deserialize(serialize(deserialize(serialize(loaded, NOW))!, NOW))).toEqual(loaded);
  });

  it('migrates each old entitlement to tier I without replaying training or roster capacity', () => {
    const before = v4().state as GameState;
    let loaded = deserialize(activeV4Text)!;
    expect(loaded.department.developmentTiers).toEqual(Object.fromEntries(before.department.unlockedNodes.map((id) => [id, 1])));
    expect(loaded.department.trainingSlots).toBe(2);
    expect(loaded.department.rosterCap).toBe(18);
    loaded = apply(loaded, { type: 'unlockNode', nodeId: 'personnel_academy', expectedTier: 2 });
    expect(loaded.department.trainingSlots).toBe(3);
    expect(loaded.department.rosterCap).toBe(18);
    expect(loaded.department.devPoints).toBe(before.department.devPoints - 4);
    expect(loaded.department.funding).toBe(before.department.funding + 160 - 4000);
    expect(deserialize(serialize(loaded, NOW))).toEqual(loaded);
  });

  it('deduplicates historical entitlements but rejects duplicate current entitlements', () => {
    const raw = v4();
    raw.state.department.unlockedNodes.push('personnel_academy');
    const loaded = deserialize(JSON.stringify(raw))!;
    expect(loaded.department.unlockedNodes.filter((id) => id === 'personnel_academy')).toHaveLength(1);
    expect(loaded.department.trainingSlots).toBe(2);
    loaded.department.unlockedNodes.push('personnel_academy');
    expect(deserialize(serialize(loaded, NOW))).toBeNull();
  });

  it.each(['ready', 'reserved', 'expired', 'service', 'scrapped'] as const)('does not refund a historically consumed battery even if its status is %s', (status) => {
    const raw = v4();
    const used = raw.state.activeRun.history[1].unitsUsed.find((id: string) => raw.state.units[id]?.itemId === 'battery_pack');
    raw.state.units[used].status = status;
    const loaded = deserialize(JSON.stringify(raw))!;
    expect(loaded.department.funding).toBe(raw.state.department.funding + 160);
    expect(loaded.equipmentPowerUpgrade).toEqual({ retiredUnits: 6, refundedFunding: 160 });
  });

  it.each([
    ['bad legacy battery', (raw: any) => { raw.state.units[Object.keys(raw.state.units).find((id) => raw.state.units[id].itemId === 'battery_pack')!].condition = 'unknown'; }],
    ['unknown legacy item', (raw: any) => { raw.state.units.unit_1.itemId = 'unreleased_device'; }],
    ['future envelope content', (raw: any) => { raw.contentVersion = INCIDENT_CONTENT_VERSION + 1; }],
    ['future state content', (raw: any) => { raw.state.contentVersion = INCIDENT_CONTENT_VERSION + 1; }],
    ['fractional content', (raw: any) => { raw.contentVersion = 1.5; }],
    ['future save', (raw: any) => { raw.saveVersion = CURRENT_SAVE_VERSION + 1; }],
    ['zero-time resupply', (raw: any) => { raw.state.activeRun.resupplies[0].minutes = 0; }],
    ['malformed resupply', (raw: any) => { raw.state.activeRun.resupplies[0].allocations[0].unitIds = null; }],
  ] as const)('rejects %s before retiring units or claiming a refund', (_name, mutate) => {
    const raw = v4(); mutate(raw);
    expect(deserialize(JSON.stringify(raw))).toBeNull();
  });
});

describe('v1 stack migration against frozen legacy output', () => {
  it('preserves the old ID, wear, aging, career, incident and RNG sequence across retired battery stacks', () => {
    const baseline = JSON.parse(expectedV4Text) as GameState;
    expect(batteries(baseline)).toHaveLength(5);
    const loaded = deserialize(stacksV1Text)!;
    expect(loaded).not.toBeNull();
    expect(loaded).toEqual({
      ...baseline,
      saveVersion: 5,
      contentVersion: INCIDENT_CONTENT_VERSION,
      department: { ...baseline.department, funding: baseline.department.funding + 200, developmentTiers: { personnel_academy: 1 } },
      units: Object.fromEntries(Object.entries(baseline.units).filter(([, unit]) => unit.itemId !== 'battery_pack')),
      equipmentPowerUpgrade: { retiredUnits: 5, refundedFunding: 200 },
    });
    expect(loaded.activeRun).toBeNull();
    expect(loaded.reservations).toEqual([]);
    expect(loaded.officers.off_chen.assignment).toBeNull();
    expect(Object.values(loaded.units).filter((unit) => unit.status === 'service')).toHaveLength(2);
    expect(deserialize(serialize(loaded, NOW))).toEqual(loaded);
  });
});

describe('saved decision detail and optional arrangement metadata', () => {
  it('round-trips committed results and the detached finished decision log', () => {
    const current = currentDecisionState();
    const loaded = deserialize(serialize(current, NOW))!;
    expect(loaded).toEqual(current);
    expect(decisionViews(loaded)).toEqual(decisionViews(current));
    const finished = playPolicy(loaded, {}).state;
    expect(finished.debriefs[0].endingSummary).toBeTruthy();
    expect(finished.debriefs[0].decisions!.length).toBeGreaterThan(0);
    expect(deserialize(serialize(finished, NOW))).toEqual(finished);
  });

  it.each([
    ['missing actual delta', (state: any) => { delete state.activeRun.history[0].committed.objectiveDelta; }],
    ['invalid ending label', (state: any) => { state.activeRun.history[0].committed.endingTitle = {}; }],
    ['invalid consequences', (state: any) => { state.activeRun.history[0].committed.consequences = [null]; }],
  ] as const)('rejects malformed committed result: %s', (_name, mutate) => {
    const state = currentDecisionState(); mutate(state);
    expect(deserialize(serialize(state, NOW))).toBeNull();
  });

  it.each([
    ['ending summary', (state: any) => { state.debriefs[0].endingSummary = []; }],
    ['decision collection', (state: any) => { state.debriefs[0].decisions = [null]; }],
    ['negative supply count', (state: any) => { state.debriefs[0].decisions[0].supplies = [{ itemId: 'trauma_kit', label: 'Trauma kit', qty: -1 }]; }],
    ['malformed contributor', (state: any) => { state.debriefs[0].decisions[0].contributors = [{ label: 'Invalid', value: 1, source: 'unknown' }]; }],
    ['malformed knowledge', (state: any) => { state.debriefs[0].decisions[0].knowledgeChanges = [{ factId: 'fact', label: 'Fact', status: 'certain' }]; }],
    ['untyped strain flag', (state: any) => { state.debriefs[0].decisions[0].actualStressDeltas = 'yes'; }],
  ] as const)('rejects malformed saved decision detail: %s', (_name, mutate) => {
    const state = playPolicy(currentDecisionState(), {}).state; mutate(state);
    expect(deserialize(serialize(state, NOW))).toBeNull();
  });

  it('preserves valid protections and Undo through a save round trip', () => {
    const state = createInitialState(NOW, 21);
    const topology = squadTopology(state);
    state.squadArrangement = { officerLocks: ['off_chen'], squadLocks: ['A'], undo: { before: topology, after: topology } };
    expect(deserialize(serialize(state, NOW))).toEqual(state);
  });

  it.each([null, 7, [], 'not an object'])('discards malformed optional arrangement data (%j) without discarding the campaign', (metadata) => {
    const state = createInitialState(NOW, 21);
    const raw = JSON.parse(serialize(state, NOW)); raw.state.squadArrangement = metadata;
    expect(deserialize(JSON.stringify(raw))).toEqual(state);
  });

  it('normalizes unknown and duplicate locks, discarding corrupt Undo while preserving valid locks', () => {
    const state = createInitialState(NOW, 21);
    const raw = JSON.parse(serialize(state, NOW));
    raw.state.squadArrangement = {
      officerLocks: ['off_chen', 'missing_officer', 'off_chen', null, '__proto__', 'constructor'],
      squadLocks: ['A', 'missing_squad', 'A', null], undo: { before: null, after: {} },
    };
    expect(deserialize(JSON.stringify(raw))).toEqual({ ...state, squadArrangement: { officerLocks: ['off_chen'], squadLocks: ['A'] } });
  });

  it('rejects invalid core state before consulting optional arrangement metadata', () => {
    const raw = JSON.parse(serialize(createInitialState(NOW, 21), NOW));
    raw.state.officers = null;
    raw.state.squadArrangement = { officerLocks: ['off_chen'], squadLocks: ['A'], undo: {} };
    expect(() => deserialize(JSON.stringify(raw))).not.toThrow();
    expect(deserialize(JSON.stringify(raw))).toBeNull();
  });
});
